name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create config.js
      run: |
        echo "export const firebaseConfig = {" > ./config.js
        echo "  apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> ./config.js
        echo "  authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> ./config.js
        echo "  databaseURL: 'https://listapeliculas-294af-default-rtdb.firebaseio.com'," >> ./config.js
        echo "  projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> ./config.js
        echo "  storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> ./config.js
        echo "  messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> ./config.js
        echo "  appId: '${{ secrets.FIREBASE_APP_ID }}'," >> ./config.js
        echo "  measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'" >> ./config.js
        echo "};" >> ./config.js
        echo "" >> ./config.js
        echo "export const rapidApiConfig = {" >> ./config.js
        echo "  apiKey: '${{ secrets.API_RAPID }}'," >> ./config.js
        echo "  apiHost: '${{ secrets.API_HOST }}'" >> ./config.js
        echo "};" >> ./config.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./

    - name: Set environment URL
      id: deployment
      run: echo "url=${{ github.event.repository.html_url }}" >> $GITHUB_ENV

    # - name: Output environment URL
    #   run: echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
